create table USERS
(
    ID             BIGINT       NOT NULL AUTO_INCREMENT,
    USERNAME       VARCHAR(15)  NOT NULL,
    PASSWORD       VARCHAR(255) NOT NULL,
    EMAIL          VARCHAR(30)  NOT NULL,
    PHONE_NUMBER   VARCHAR(15)  NOT NULL,
    NAME           VARCHAR(15)  NOT NULL,
    LAST_NAME      VARCHAR(15)  NOT NULL,
    AVATAR         BLOB,
    USER_ROLE      ENUM ('USER','TRAINER'),
    ACCOUNT_STATUS BOOLEAN      NOT NULL,
    PRIMARY KEY (ID)
);
create table PETS
(
    ID           BIGINT                     NOT NULL AUTO_INCREMENT,
    NAME         VARCHAR(15)                NOT NULL,
    RACE         VARCHAR(15)                NOT NULL,
    DESCRIPTION  VARCHAR(30),
    PREFERENCES  VARCHAR(30),
    RESTRICTIONS VARCHAR(30),
    AVATAR       BLOB,
    PET_STATUS   ENUM ('ACTIVE','ARCHIVED') NOT NULL,
    USER_ID      BIGINT                     NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PETS_USERS
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
);
-- create table USERS_PETS
-- (
--     ID      BIGINT NOT NULL AUTO_INCREMENT,
--     USER_ID BIGINT NOT NULL,
--     PET_ID  BIGINT NOT NULL,
--     PRIMARY KEY (ID),
--     CONSTRAINT USER_PET
--         FOREIGN KEY (ID)
--             REFERENCES PETS (ID),
--     CONSTRAINT PET_USER
--         FOREIGN KEY (ID)
--             REFERENCES USERS (ID)
-- );
create table TRAINER
(
    ID             BIGINT       NOT NULL AUTO_INCREMENT,
    USERNAME       VARCHAR(15)  NOT NULL,
    PASSWORD       VARCHAR(255) NOT NULL,
    EMAIL          VARCHAR(15)  NOT NULL,
    PHONE_NUMBER   VARCHAR(15)  NOT NULL,
    NAME           VARCHAR(15)  NOT NULL,
    LAST_NAME      VARCHAR(15)  NOT NULL,
    EXPERIENCE     VARCHAR(150),
    AVATAR         BLOB,
    USER_ROLE      ENUM ('USER','TRAINER'),
    ACCOUNT_STATUS BOOLEAN      NOT NULL,
    PRIMARY KEY (ID)
);
create table WALK_SLOTS
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    REAL_DAY DATE NOT NULL,
    START_DATE DATETIME   NOT NULL,
    TRAINER_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT WALK_SLOTS_TRAINER
        FOREIGN KEY (TRAINER_ID)
            REFERENCES TRAINER (ID)
);
create table WALK
(
    ID          BIGINT NOT NULL AUTO_INCREMENT,
    WALK_SLOTS_ID BIGINT NOT NULL,
    PET_ID      BIGINT NOT NULL,
    WALK_STATUS ENUM ('PLANNED','IN_PROGRESS','FINISHED','CANCELLED'),
    PRIMARY KEY (ID),
    CONSTRAINT WALK_WALK_SLOTS_ID
        FOREIGN KEY (WALK_SLOTS_ID)
            REFERENCES WALK_SLOTS (ID),
    CONSTRAINT WALK_PETS
        FOREIGN KEY (PET_ID)
            REFERENCES PETS (ID)
    );
create table WALK_REVIEW
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    RATE    INT    NOT NULL,
    COMMENT VARCHAR(255),
    USER_ID BIGINT NOT NULL,
    WALK_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT WALK_REVIEW_USER_ID
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID),
    CONSTRAINT WALK_REVIEW_WALK_ID
        FOREIGN KEY (WALK_ID)
            REFERENCES WALK (ID)
);
create table CONFIRMATION_TOKEN
(
    ID           BIGINT       NOT NULL AUTO_INCREMENT,
    TOKEN        VARCHAR(255) NOT NULL,
    CREATED_AT   DATETIME         NOT NULL,
    EXPIRES_AT   DATETIME         NOT NULL,
    CONFIRMED_AT DATETIME,
    USER_ID      BIGINT         NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CONFIRMATION_TOKEN_USERS
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
);

